### ISSUE TITLE
所属班の表示を未実装であることがわかるように変更する

### ISSUE THREAD

**Issue by ras0q** [traPtitech/traPortfolio-UI#188]
班
現在所属している班はありません

となっているがdashで班情報は変更できないので「班情報の取得は実装予定です」とかにしてほしい

**Comment by mehm8128** [comment]
あれ、traQから取ってくる情報で表示できないんでしたっけ？

**Comment by ras0q** [comment]
バックエンドが未実装か
どっちにしても未実装なので一時的に表示を変更しておいてほしいです

今はtpf固有でgroupを持っているがtraPの班以外のgroupはいらないので自動取得するって方針でいいんでしたっけ

**Comment by mehm8128** [comment]
基本的にはそれで合ってて、優先度は低めですが元リーダーみたいな表示もしたいのでそこはtpf側で持っておきたいというのもあります
