### ISSUE TITLE
プロジェクト期間の仕様変更への対応

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/traPortfolio-UI#33]
https://github.com/traPtitech/traPortfolio/pull/78

**Comment by toshi-pono** [comment]
確認したのですが，現状で修正するところはなさそうです．
https://github.com/traPtitech/traPortfolio/pull/25 でプロジェクト期間の仕様変更が入った後に，Project一覧ページを製作しているので問題なさそうです．プロジェクトのdurationを使っているのが src/components/Projects/ProjectListItem.vue だけで，ここは {{year}}前期 みたいなかんじで想定通りに動いていました．

**Comment by sapphi-red** [comment]
あ、これ確かに編集系のAPIだけですね
:kansya:
